package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"gopkg.in/yaml.v3"
)

type pluginConfig struct {
	Plugins []string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}

	modulePath, err := readModulePath(filepath.Join(root, "go.mod"))
	if err != nil {
		return err
	}

	configPath := filepath.Join(root, "plugin.yaml")
	config, err := parsePluginConfig(configPath)
	if err != nil {
		return err
	}

	imports, err := resolveImports(root, modulePath, config.Plugins)
	if err != nil {
		return err
	}

	outputPath := filepath.Join(root, "cmd", "proxygw", "plugin.go")
	return writePluginFile(outputPath, imports)
}

func repoRoot() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", errors.New("failed to determine generator location")
	}
	return filepath.Dir(filepath.Dir(filepath.Dir(file))), nil
}

func readModulePath(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}

	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(strings.TrimRight(line, "\r"))
		if !strings.HasPrefix(trimmed, "module ") {
			continue
		}

		modulePath := strings.TrimSpace(strings.TrimPrefix(trimmed, "module "))
		if modulePath == "" {
			return "", fmt.Errorf("%s: empty module path", path)
		}
		return modulePath, nil
	}

	return "", fmt.Errorf("%s: module directive not found", path)
}

func parsePluginConfig(path string) (pluginConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return pluginConfig{}, fmt.Errorf("read %s: %w", path, err)
	}

	var config pluginConfig
	if err := yaml.Unmarshal(data, &config); err != nil {
		return pluginConfig{}, fmt.Errorf("parse %s: %w", path, err)
	}
	if len(config.Plugins) == 0 {
		return pluginConfig{}, fmt.Errorf("%s: plugins list is empty", path)
	}

	for i, plugin := range config.Plugins {
		if strings.TrimSpace(plugin) == "" {
			return pluginConfig{}, fmt.Errorf("%s: plugins[%d] is empty", path, i)
		}
	}

	return config, nil
}

func resolveImports(root, modulePath string, plugins []string) ([]string, error) {
	imports := make([]string, 0, len(plugins))
	for _, plugin := range plugins {
		if plugin == "" {
			return nil, errors.New("plugin entry must not be empty")
		}

		localPath := filepath.Join(root, "plugin", filepath.FromSlash(plugin))
		if info, err := os.Stat(localPath); err == nil && info.IsDir() {
			imports = append(imports, filepath.ToSlash(filepath.Join(modulePath, "plugin", filepath.FromSlash(plugin))))
			continue
		}

		imports = append(imports, plugin)
	}
	return imports, nil
}

func writePluginFile(path string, imports []string) error {
	var buf bytes.Buffer
	buf.WriteString("package main\n\n")
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	buf.WriteString("import (\n")
	for _, importPath := range imports {
		buf.WriteString(fmt.Sprintf("\t_ %q\n", importPath))
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated file: %w", err)
	}

	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
