package main

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"gopkg.in/yaml.v3"
)

type pluginModule struct {
	Reference string
	Version   string
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repoRoot()
	if err != nil {
		return err
	}

	modulePath, err := readModulePath(filepath.Join(root, "go.mod"))
	if err != nil {
		return err
	}

	configPath := filepath.Join(root, "plugin.yaml")
	config, err := parsePluginConfig(configPath)
	if err != nil {
		return err
	}

	imports, err := resolveImports(root, modulePath, config)
	if err != nil {
		return err
	}

	outputPath := filepath.Join(root, "cmd", "proxygw", "plugin.go")
	return writePluginFile(outputPath, imports)
}

func repoRoot() (string, error) {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", errors.New("failed to determine generator location")
	}
	return filepath.Dir(filepath.Dir(filepath.Dir(file))), nil
}

func readModulePath(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", path, err)
	}

	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(strings.TrimRight(line, "\r"))
		if !strings.HasPrefix(trimmed, "module ") {
			continue
		}

		modulePath := strings.TrimSpace(strings.TrimPrefix(trimmed, "module "))
		if modulePath == "" {
			return "", fmt.Errorf("%s: empty module path", path)
		}
		return modulePath, nil
	}

	return "", fmt.Errorf("%s: module directive not found", path)
}

func parsePluginConfig(path string) ([]pluginModule, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}

	config := make(map[string]string)
	if err = yaml.Unmarshal(data, config); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if len(config) == 0 {
		return nil, fmt.Errorf("%s: plugin mapping is empty", path)
	}

	modules := make([]pluginModule, 0, len(config))
	for ref, version := range config {
		ref = strings.TrimSpace(ref)
		if ref == "" {
			return nil, fmt.Errorf("%s: module reference is empty", path)
		}

		version = strings.TrimSpace(version)
		if version == "" {
			return nil, fmt.Errorf("%s: version for module %q is empty", path, ref)
		}

		modules = append(modules, pluginModule{
			Reference: ref,
			Version:   version,
		})
	}

	return modules, nil
}

func resolveImports(root, modulePath string, plugins []pluginModule) ([]string, error) {
	imports := make([]string, 0, len(plugins))
	for _, plugin := range plugins {
		if plugin.Reference == "" {
			return nil, errors.New("plugin entry must not be empty")
		}

		if plugin.Version != "builtin" {
			imports = append(imports, plugin.Reference)
			continue
		}

		localPath := filepath.Join(root, "plugin", filepath.FromSlash(plugin.Reference))
		if info, err := os.Stat(localPath); err == nil && info.IsDir() {
			imports = append(imports, filepath.ToSlash(filepath.Join(modulePath, "plugin", filepath.FromSlash(plugin.Reference))))
			continue
		}

		return nil, fmt.Errorf("builtin plugin %q not found under %s", plugin.Reference, filepath.Join(root, "plugin"))
	}
	return imports, nil
}

func writePluginFile(path string, imports []string) error {
	var buf bytes.Buffer
	buf.WriteString("package main\n\n")
	buf.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	buf.WriteString("import (\n")
	for _, importPath := range imports {
		buf.WriteString(fmt.Sprintf("\t_ %q\n", importPath))
	}
	buf.WriteString(")\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated file: %w", err)
	}

	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}
