$schema: "https://json-schema.org/draft/2020-12/schema"
title: Plugin Configuration
type: object
additionalProperties: false
required:
  - plugins
properties:
  plugins:
    type: array
    items:
      type: string
